services:
  postgres:
    image: postgres:17
    restart: unless-stopped
    container_name: educacidades-database
    env_file: ./.env
    ports:
      - $POSTGRES_LOCAL_PORT:$POSTGRES_DOCKER_PORT
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DATABASE
    volumes:
      - postgresvolume:/var/lib/postgresql

  backend:
    depends_on:
      - postgres
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /usr/src/educacidadesapp
    container_name: educacidades-backend
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/$POSTGRES_DATABASE?useSSL=false&createDatabaseIfNotExist=true

      - SPRING_DATASOURCE_USERNAME=$POSTGRES_USER
      - SPRING_DATASOURCE_PASSWORD=$POSTGRES_PASSWORD
    stdin_open: true
    tty: true

volumes:
  postgresvolume: